config/routes.rb
Rails.application.routes.draw do
  root 'diaries#index'
  resources :diaries do
    collection do
      get :set_map_session, to: 'diaries#set_map_session'
    end
    resources :map_session, only: :create
  end


  # get '/search_content', to: 'searches#index' 
  resource :search, only: [:new,:show,:create]

  resources :settings

  resource :tag
  resources :drafts
  resources :pictures
  resources :pockets
  devise_for :users
  resources :users
  get "/ajax", to: "users#ajax"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/diary.rb
class Diary < ApplicationRecord
  default_scope { order('diary_date desc') }
  validates :diary_date, presence: true
  has_one_attached :picture
  has_many :diary_tags
  has_many :tags, through: :diary_tags
  belongs_to :user


  def week
    date = diary_date.days_to_week_start
    case date
    when 0
      return '一'
    when 1
      return '二'
    when 2
      return '三'
    when 3
      return '四'
    when 4
      return '五'
    when 5
      return '六'
    when 6
      return '日'
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @drafts = current_user.diaries.where(is_published: false).order(:diary_date).limit(3)
    @pockets = current_user.pocket_lists.order(created_at: :asc).limit(3)
    @diaries = current_user.diaries.with_attached_picture.where(is_published: true).order(:diary_date)
  end

  def show
    @diary = current_user.diaries.find_by(id: params[:id])
    @drafts = current_user.diaries.where(is_published: false).order(:diary_date).limit(3)
    @pockets = current_user.pocket_lists.order(created_at: :asc).limit(3)
    @tag_items = @diary.tags

  end

  def new
    @diary = current_user.diaries.new(diary_date: Time.now)
    @drafts = current_user.diaries.where(is_published: false).order(:diary_date).limit(3)
    @diary = current_user.diaries.new(diary_date: Time.now)
    @pockets = current_user.pocket_lists.order(created_at: :asc).limit(3)
    if params[:delete_session]
      session.delete(:location)
    end

    if session[:location].present?
      @diary.location = session[:location]
      # session.delete(:location)
    end
    
    items = []
    @tag_items = []
    @user_tags = current_user.tags
  end


  def create
    @diary = current_user.diaries.new(diary_params)
    @diary.is_published=true if params[:is_published] == 'true'
    @diary.is_published=false if params[:is_published] == 'false'
    items = params[:label]
    @tag_items = []
    @user_tags = current_user.tags
    # @picture = Picture.new(diary_params)
    @diary.location = session[:location]

    # binding.pry
    if @diary.save
      unless items.nil?
        items.each do |item|
          current_user.tags.find_or_create_by(label: item)
          tag_id = current_user.tags.find_by(label: item).id
          DiaryTag.create(diary_id: @diary.id, tag_id: tag_id)
        end
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @diary = current_user.diaries.find_by(id: params[:id])
    @drafts = current_user.diaries.where(is_published: false).order(:diary_date).limit(3)
    @pockets = current_user.pocket_lists.order(created_at: :asc).limit(3)
    items = []
    @tag_items = @diary.tags

    @user_tags = current_user.tags - @tag_items
    render :new
    
  end
  
  def update
    @diary = current_user.diaries.find_by(id: params[:id])
    @diary.is_published= true if params[:is_published] == 'true'
    @diary.is_published= false if params[:is_published] == 'false'
    @tag_items = @diary.tags
    items = params[:label]
    
    @user_tags = current_user.tags - @tag_items
    
    diary_tags = @diary.diary_tags
    if @diary.update(diary_params)
      unless diary_tags.nil?
        diary_tags.each do |item|
          item.destroy
        end
      end
      unless items.nil?
        items.each do |item|
          current_user.tags.find_or_create_by(label: item)
          tag_id = current_user.tags.find_by(label: item).id
          DiaryTag.create(diary_id: @diary.id, tag_id: tag_id)
        end
      end
      
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @diary = current_user.diaries.find_by(id: params[:id])
    diary_tags = @diary.diary_tags
    unless diary_tags == []
      diary_tags.each do |item|
        item.destroy
      end
    end
    @diary.destroy if @diary
    redirect_to root_path
  end
  
  def set_map_session
    location_params = params.permit(location: {})
    session[:location] = location_params[:location]
  end

  private
  def diary_params
    # params.require(:diary).permit(:content,:location,:diary_date,:cover)
    params.require(:diary).permit(:content,:location,:diary_date,:picture)
  end

  

end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_map.html.erb
<style>
    #map {
        height: 300px;
        width: 100%;
    }

    #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto', 'sans-serif';
        line-height: 30px;
        padding-left: 10px;
    }
</style>
<div id="map">
</div>
<script>
    var lat = parseFloat("<%= @diary.location['lat'] %>");
    var lng = parseFloat("<%= @diary.location['lng'] %>");
    var placeId = "<%= @diary.location['place_id'] %>";
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: { lat: lat, lng: lng }
        });
        var geocoder = new google.maps.Geocoder;
        var infowindow = new google.maps.InfoWindow;
        geocodePlaceId(geocoder, map, infowindow);
    }

    function geocodePlaceId(geocoder, map, infowindow) {
        geocoder.geocode({ 'placeId': placeId }, function (results, status) {
            if (status === 'OK') {
                if (results[0]) {
                    map.setZoom(14);
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location
                    });
                    infowindow.setContent(results[0].formatted_address);
                    infowindow.open(map, marker);
                } else {
                    infowindow.setContent('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= Figaro.env.google_api_key %>&callback=initMap">
</script>

app/views/diaries/_nav.html.erb
<div class="navbox">
  <nav class="nav show-in-pc">
    <ul>
      <li><%= link_to 'Explore', users_path %></li>
      <li><%= link_to 'Pocket', '#' %></li>
      <li><%= link_to 'Diary', new_diary_path %></li>
      <li><%= link_to 'Draft', '#' %></li>
      <li><%= link_to 'Setting', '#' %></li>
    </ul>
  </nav>
</div>

app/views/diaries/index.html.erb
<div class="diarywrap">

  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">

    <section class="main">
      <% current_year = 0 %>
      <% current_month = 0 %>
      <% @diaries.each do |diary| %>
      <div>

        <% if current_year != diary.diary_date.year || current_month != diary.diary_date.month %>
        <% current_year = diary.diary_date.year %>
        <% current_month = diary.diary_date.month %>
        <span class="year"><%= diary.diary_date.year %></span>
        <span class="month"><%= diary.diary_date.month %></span>
        <% end %>
      </div>
      <%= link_to diary_path(diary),class:'diary' do %>
      <div class="items">
        <div class="date">
          <span class="day"><%= diary.diary_date.day %></span>
          <span class="week"><%= diary.week %></span>
        </div>

        <div class="info">
          <div class="content">
            <%= simple_format(excerpt(diary.content,'',radius: 20)) %>
          </div>
          <% if diary.location.try(:[], 'address') %>
          <div class="location">
            <%= diary.location.try(:[], 'address')  %>
          </div>
          <% end %>
        </div>

        <div class="pic">
          <%= image_tag diary.picture.service_url if diary.picture.attached? %>
        </div>

      </div>
      <% end %>
      <% end %>
    </section>

    <section class="sidebar">
      <%= render 'layouts/sidepocket' %>
      <%= render 'layouts/sidedraft' %>
    </section>

  </div>

</div>

app/views/diaries/new.html.erb
<div class="diarywrap">
  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">

    <section class="main form">
      <%= simple_form_for @diary do |form| %>

      <div class="form-pic">


        <div>
          <img class="preview">
          <div class="size"></div>
        </div>
        <div class="upload-btn">
          <%= form.label(:picture)  do %>
            <div class="btn">選擇照片</div>
          <% end %>
          <%= form.file_field :picture, class: 'upl pic', style: 'display:none;' %>
          
        </div>
      </div>



      <div class="form-date">
        <%= form.input :diary_date, as: :date, html5: true,label: false %></div>

      <div class="form-location">

        <% if @diary.location.try(:[],"name") %>
        <h1><%= @diary.location.try(:[],"name") %></h1>
        <%= render 'diaries/map' %>
        <% end %>
      </div>

      <div class="form-content"><%= form.input :content, label: false, placeholder: '記錄點什麼吧^_^' %></div>
      
        <div class="hidden_form">
        </div>


      <div class="form-tag">

        <div class="tags TagItems">
        <% unless @tag_items.nil? %>
          <% @tag_items.each do |tag| %>
            <span class="tag-item"><%= tag.label %></span>
          <% end %>
        <% end %>
        </div>




        <div class="tags UserTags">
          <% @user_tags.each do |tag| %>
          <span class="tag-item"><%= tag.label %></span>
          <% end %>
        </div>
        <div class="tags NewTag">
          <input type="text" placeholder="輸入Tag" id="tagInput" class="">
          <input type="button" value="新增自訂標籤" id="tagBtn" class="btn btn-primary">
        </div>

      </div>

      <section class="btn-link">
        <input type="hidden" id="is_published" name="is_published" value="false" />
        <% if action_name == 'edit' %>
        <%= link_to '返回', diary_path, class:'btn btn-secondary btn-linkto', data: { confirm: '日記正在編輯中，尚未儲存，是否放棄編輯？'} %>
        <%= form.button :submit, '稍後編輯', class:'btn btn-secondary js-submit', data: { is_published: false }  %>
        <%= form.button :submit,'確定修改' , class:'btn btn-primary js-submit', data: { is_published: true } %>
        <% else %>
        <%= link_to '返回', root_path, class:'btn btn-secondary btn-linkto' %>
        <%= form.button :submit, '稍後編輯', class:'btn btn-secondary js-submit', data: { is_published: false }  %>
        <%= form.button :submit,'新增' , class:'btn btn-primary js-submit', data: { is_published: true } %>
        <% end %>
      </section>




    </section>

    <% end %>

    <section class="sidebar">
      <%= render 'layouts/sidepocket' %>
      <%= render 'layouts/sidedraft' %>
    </section>

  </div>
</div>

<script>

$(document).ready(function(){
  // setting submit value
  $('.js-submit').click(function(){
    var $this = $(this)
    $('#is_published').val($this.data('is-published'))
  })



  // init origin tags data
  var originTags;
  var originUserTags;

  if ($('.TagItems .tag-item').length!=0){
    originTags = $('.TagItems').get()[0].innerText.split("\n")
    originTags.forEach(function(item){
      createHiddenInput(item)
    })
  }

  if ($('.UserTags .tag-item').length!=0){
    originUserTags = $('.UserTags').get()[0].innerText.split(" ")
  }

  $('.TagItems').on('click','.tag-item',function(){
    var $this = $(this)
    var $tagObj = $this.context.innerHTML
    var tagSpan = "<span class='tag-item'>" + $tagObj + "</span>"
    $('.UserTags').append(tagSpan)
    removeHiddenInput($tagObj)
    $this.remove()
  })

  $('.UserTags').on('click','.tag-item',function(){
    var $this = $(this)
    var $tagObj = $this.context.innerHTML
    var tagSpan = "<span class='tag-item'>"+ $tagObj +"</span>"
    $('.TagItems').append(tagSpan)
    createHiddenInput($tagObj)
    $this.remove()
  })

  $('#tagBtn').on('click',function(){
    let tagRgx = /\s/
    var tagInput = $('#tagInput').val()
    if (tagInput.match(tagRgx)){
      alert('標籤不能有空白字元喔')
    }else{
      var tagSpan = "<span class='tag-item'>"+ tagInput +"</span>"
      $('.TagItems').append(tagSpan)
      createHiddenInput(tagInput)
      $('#tagInput').val('')
    }
  })


function createHiddenInput(item){
  let HiddenInput = "<input type='hidden' name='label[]' value='"+ item +"'>"
  $('.hidden_form').append(HiddenInput)
}
function removeHiddenInput(item){
  var $removeInput = $(".hidden_form input[value='" + item + "']")
  $removeInput.remove()
}
});
</script> 

app/views/diaries/show.html.erb
<div class="diarywrap">

  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">
    <section class="main">
      <section class="show-diary">
        <div class="picture"><%= image_tag @diary.picture.service_url if @diary.picture.attached? %></div>
        <div class="location">
          <% if @diary.location.try(:[],"name") %>
          <h1><%= @diary.location.try(:[],"name") %></h1>
          <%= render 'diaries/map' %>
          <% end %>
        </div>
        <div class="date">
          <%= @diary.diary_date.year %>年
          <%= @diary.diary_date.month %>月
          <%= @diary.diary_date.day %>日
          星期<%= @diary.week %>
        </div>

        <div class="content"><%= @diary.content %></div>
        <div class="tags">
          <% @tag_items.each do |tag| %>
          <span class="tag-item"><%= tag.label %></span>
          <% end %>
        </div>
        <section class="btn-link">
          <%= link_to '返回', root_path, class:'btn btn-secondary' %>
          <%= link_to '刪除', diary_path, method:'delete', class:'btn btn-danger', data:{ confirm:'確定刪除？' } %>
          <%= link_to '修改', edit_diary_path, class:'btn btn-primary' %>
        </section>
      </section>



    </section>

    <section class="sidebar">
      <%= render 'layouts/sidepocket' %>
      <%= render 'layouts/sidedraft' %>
    </section>
  </div>


</div>