config/routes.rb
Rails.application.routes.draw do
  root 'diaries#index'
  resources :diaries do
    collection do
      get :set_map_session, to: 'diaries#set_map_session'
    end
    resources :map_session, only: :create
  end


  # get '/search_content', to: 'searches#index' 
  resource :search, only: [:new,:show,:create]

  resources :settings

  resource :tag
  resources :drafts
  resources :pictures
  resources :pockets
  devise_for :users
  resources :users
  get "/ajax", to: "users#ajax"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries
  has_many :tags
  has_many :pocket_lists
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # session.delete(:location) if session[:location].present?
  end

  def ajax
    # @location_x = params[:lat]
    # @location_y = params[:lng]

    #@locations = Location.new(lat: params[:lat], lng: params[:lng])
    #@locations.save!

    @diaries = Diary.new(location: diary_params[:location], diary_date: '2019-06-03 00:00:00')
    @diaries.user = current_user
  end

  def diary_params
    params.permit(location: {})
  end
end

app/views/users/index.html.erb
<div class="diarywrap">
  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">
    <section class="main form">
      <div class="loader-box">
        <div class="loader-flex">
          <div class="loading"></div>
        </div>
      </div>
      <div id="map"></div>
      <section class="btn-link map-link">
      <div class="choose"></div>
        <%= link_to '新增日記', new_diary_path, class:'btn btn-secondary btn-linkto new_diary' %>
        <%= link_to '加入口袋', new_pocket_path, class:'btn btn-secondary btn-linkto new_pocket' %>
      </section>
    </section>
    <section class="sidebar map-sidebar">
      <div id="places" class="places"></div>
    </section>
  </div>
</div>
<script type="text/javascript">
  var map, infoWindow, address, address_contury, address_area;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
    });

    navigator.geolocation.getCurrentPosition(function (position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      map.setCenter(pos);
      // 控制拿到資料之後要多轉的時間
      $('.loader-box').delay(500).queue(function (next) {
        $(this).hide();
      });
    });

    var geocoder = new google.maps.Geocoder();
    let service = new google.maps.places.PlacesService(map);
    infoWindow = new google.maps.InfoWindow;

    //#<!-- 自選座標 -->
    map.addListener('click', function (e) {
      $('#places').empty();
      //alert(e.latLng);
      let lat = e.latLng.lat();
      let lng = e.latLng.lng();
      pyrmont = { lat: lat, lng: lng };
      service.nearbySearch(
        { location: pyrmont, radius: 20 },
        function (results, status, pagination) {
          if (status !== 'OK') return;
          createMarkers(results);
          //console.log(results);
        });
      function createMarkers(places) {
        var bounds = new google.maps.LatLngBounds();
        var placesList = document.getElementById('places');
        //console.log(placesList);
        fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&language=zh-TW&key=<%= Figaro.env.google_api_key %>`)
          .then(function (response) {
            return response.json();
          })
          .then(function (data) {
            //console.log(data);
            //縣市、區域、地址、座標
            //adress
            //$('.sidebar').append(`<div>${data.results[0].formatted_address}</div>`);
            address = data.results[0].formatted_address;
            //address_contury = data.results[0].address_components[3].long_name;
            //address_area = data.results[0].address_components[2].long_name;
            //console.log(address_contury);
            //console.log(address_area);
            placeMarkerAndPanTo(e.latLng, map);
            //市+區
            //$('#contury_area').empty().append(`<div>${address_contury}</div><div>${address_area}</div>`);

            //alert(address);
          })
          .catch(function (error) {
            alert('some bad thing happend')
            alert(error)
          })

        console.log(places);
        for (var i = 0, place; place = places[i]; i++) {
          var image = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          var marker = new google.maps.Marker({
            map: map,
            icon: image,
            title: place.name,
            position: place.geometry.location
          });

          //var geoAddress;
          // geocoder.geocode({ 'placeId': place.place_id }, function (results) {
          //    geoAddress = JSON.stringify(results[0].formatted_address);
          //    console.log(geoAddress);
          //});

          var placeStr = escape(JSON.stringify({ "name": place.name, "lat": place.geometry.location.lat(), "lng": place.geometry.location.lng(), "place_id": place.place_id, "address": place.vicinity }));
          $('#places').append(`<button type="button" class="store-places" value="${placeStr}">${place.name}</button>`);
          $('.store-places').animate({ width: "200px" }, 200);


          //$('#places').append(`<button type="button" class="store-places" value="${place.place_id}">${place.name}</button>`); -->
          //$('.sidebar').append(`<p>${e.latLng.lat()},${e.latLng.lng()}</p>`);
          //ajax
          //$.get('<%= ajax_path %>', { lat: e.latLng.lat(), lng: e.latLng.lng() });

          bounds.extend(place.geometry.location);
        }
        map.fitBounds(bounds);
      }
    });
    //var json = { "name": place.name, "id": place_id, "lat": place.geometry.location.lat(), "lng": place.geometry.location.lng() };
    $('#places').on('click', 'button', function (event) {
      let selectpoint = $(this).text();
      //alert(`你選了『${selectpoint}』`);
      $(this).addClass('infocus');
      $('.choose').text(selectpoint);
      //e.preventDefult
      //console.log('aaa')
      //console.log('!')
      //console.log(JSON.stringify(aaa))

      //document.cookie = 'location=' + JSON.stringify(aaa);

      //$.get('<%= ajax_path %>', { location: aaa });

      //let aaa = JSON.parse($(this).val());
      //$.get('<%= new_diary_path %>', { location: aaa });
    });

    function placeMarkerAndPanTo(latLng, map) {
      var marker = new google.maps.Marker({
        position: latLng,
        map: map
      });
      add_info(latLng);
      map.panTo(latLng);
    }

    //#<!-- 結束 -->
  }

  $('.new_diary').on('click', function (event) {
    var $this = $(this);
    let aaa = JSON.parse(unescape($('.infocus').val()));
    $.get('<%= set_map_session_diaries_path %>', { location: aaa }, function (rs) {
      var href = $this.attr('href');
      if (href.length > 0)
        location.href = href;
    });
    return false;
  });


  $('.new_pocket').on('click', function (event) {
    var $this = $(this);
    let aaa = JSON.parse(unescape($('.infocus').val()));
    $.get('<%= set_map_session_diaries_path %>', { location: aaa }, function (rs) {
      var href = $this.attr('href');
      if (href.length > 0)
        location.href = href;
    });
    return false;
  });


  function add_info(pos) {
    infoWindow = new google.maps.InfoWindow;
    infoWindow.setPosition(pos);
    infoWindow.setOptions({
      pixelOffset: new google.maps.Size(0, -40)
    });
    //console.log(pos);
    infoWindow.setContent(address);
    infoWindow.open(map);
    map.setCenter(pos);
  }

  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
      'Error: The Geolocation service failed.' :
      'Error: Your browser doesn\'t support geolocation.');
    infoWindow.open(map);

  }

</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= Figaro.env.google_api_key %>&libraries=places&callback=initMap">
  </script>