config/routes.rb
Rails.application.routes.draw do
  root 'diaries#index'
  resources :diaries do
    collection do
      get :set_map_session, to: 'diaries#set_map_session'
    end
    resources :map_session, only: :create
  end


  # get '/search_content', to: 'searches#index' 
  resource :search, only: [:new,:show,:create]

  resources :settings

  resource :tag
  resources :drafts
  resources :pictures
  resources :pockets
  devise_for :users
  resources :users
  get "/ajax", to: "users#ajax"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def new
    # search_params
    @tags = current_user.tags
  end
  
  def show
    @tags = current_user.tags
    @diaries = []
    diary_ids = DiaryTag.where(tag_id: params[:format])
    
    diary_ids.each do |diary|
      @diaries << current_user.diaries.find_by(id: diary.diary_id)
    end
    
    if params[:search]
      @diaries = current_user.diaries.where('content LIKE ?', "%#{params[:search]}%")
    end
  end


  def create
    search_params
    render :new
  end
  private

  def search_params
    # 一定是有登入
    # 有搜尋文字
    if params[:search]
      # 執行搜尋，找tag或內容有 關鍵字
      # @tags = current_user.tags.where('label LIKE ?', "%#{params[:search]}%")
      @diaries = current_user.diaries.where('content LIKE ?', "%#{params[:search]}%")
    else
      # 
      @diaries = current_user.present? ? current_user.diaries : []
      # @tags = current_user.present? ? current_user.tags : []
    end
  end


end


# @tags = Tag.where('label LIKE ?', "%#{params[:search]}%").ids
# where('diaries.tag_id IN ? OR diaries.content LIKE ?',tag.ids, "%#{params[:search]}%")

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<div class="diarywrap">

  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">

    <section class="main">
    <div class="form-search">
      <%= form_tag search_content_path, method: :get do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag 'Search',class:'btn btn-primary' %>
      <% end %>
    </div>
      <% current_year = 0 %>
      <% current_month = 0 %>
      <% @diaries.each do |diary| %>
      <div>

        <% if current_year != diary.diary_date.year || current_month != diary.diary_date.month %>
        <% current_year = diary.diary_date.year %>
        <% current_month = diary.diary_date.month %>
        <span class="year"><%= diary.diary_date.year %></span>
        <span class="month"><%= diary.diary_date.month %></span>
        <% end %>
      </div>
      <%= link_to diary_path(diary),class:'diary' do %>
      <div class="items">
        <div class="date">
          <span class="day"><%= diary.diary_date.day %></span>
          <span class="week"><%= diary.week %></span>
        </div>

        <div class="info">
          <div class="content">
            <%= simple_format(excerpt(diary.content,'',radius: 20)) %>
          </div>
          <div class="location"><%= diary.location %></div>
        </div>

        <div class="pic">
          <%= image_tag diary.picture if diary.picture.attached? %>
        </div>
      </div>
      <% end %>
    <% end %>
    </section>
    <section class="sidebar">
      <div class="tags SearchTags">
        <% @tags.each do |tag| %>
          <span class="tag-item"><%= tag.label %></span>
        <% end %> 
      </div>
    </section>
  </div>
    
</div>

app/views/searches/new.html.erb
<div class="diarywrap">

  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">

    <section class="main">
    <div class="form-search">
      <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag 'Search',class:'btn btn-primary' %>
      <% end %>
    </div>
    </section>

    <section class="sidebar">
      <div class="tags SearchTags">
        <% @tags.each do |tag| %>
          <%= link_to search_path(tag.id) do %>
            <span class="tag-item"><%= tag.label %></span>
          <% end %>
        <% end %> 
      </div>
    </section>
  </div>
    
</div>

app/views/searches/show.html.erb
<div class="diarywrap">

  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <div class="container">

    <section class="main">
      <div class="form-search">
        <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag 'Search', class:'btn btn-primary' %>
        <% end %>
      </div>
      <% current_year = 0 %>
      <% current_month = 0 %>
      <% @diaries.each do |diary| %>
      <div>

        <% if current_year != diary.diary_date.year || current_month != diary.diary_date.month %>
        <% current_year = diary.diary_date.year %>
        <% current_month = diary.diary_date.month %>
        <span class="year"><%= diary.diary_date.year %></span>
        <span class="month"><%= diary.diary_date.month %></span>
        <% end %>
      </div>
      <%= link_to diary_path(diary),class:'diary' do %>
      <div class="items">
        <div class="date">
          <span class="day"><%= diary.diary_date.day %></span>
          <span class="week"><%= diary.week %></span>
        </div>

        <div class="info">
          <div class="content">
            <%= simple_format(excerpt(diary.content,'',radius: 20)) %>
          </div>
          <div class="location"><%= diary.location %></div>
        </div>

        <div class="pic">
          <%= image_tag diary.picture if diary.picture.attached? %>
        </div>
      </div>
      <% end %>
      <% end %>
    </section>
    <section class="sidebar">
      <div class="tags SearchTags">
        <% @tags.each do |tag| %>
        <%= link_to search_path(tag.id) do %>
        <span class="tag-item"><%= tag.label %></span>
        <% end %>
        <% end %>
      </div>
    </section>
  </div>

</div>