config/routes.rb
Rails.application.routes.draw do
  root 'diaries#index'
  resources :diaries do
    collection do
      get :set_map_session, to: 'diaries#set_map_session'
    end
    resources :map_session, only: :create
  end


  # get '/search_content', to: 'searches#index' 
  resource :search, only: [:new,:show,:create]

  resources :settings

  resource :tag
  resources :drafts
  resources :pictures
  resources :pockets
  devise_for :users
  resources :users
  get "/ajax", to: "users#ajax"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="headerbox">
  <div class="header">
    <ul>
      <li class='logo'><%= link_to 'GoGoDiary', root_path %></li>
      <li class='search-bar'>
        <%= link_to "Search", new_search_path %>
      </li>
      <li class='list'>
      </li>
      <li><%= link_to 'Setting', settings_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'SignOut', destroy_user_session_path, method:'delete' %></li>
      <% end %>
      <% if not user_signed_in? %>
        <li><%= link_to 'SignIn', new_user_session_path %></li>
        <li><%= link_to 'SignUp', new_user_registration_path %></li>
      <% end %>
      
    </ul>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbox">
  <nav class="nav show-in-pc">
    <ul>
      <li><%= link_to 'Explore', users_path %></li>
      <li><%= link_to 'Pockets', pockets_path %></li>
      <li class="new_diary"><%= link_to 'Diary', new_diary_path({delete_session: true}), class:'new_diary' %></li>
      <li><%= link_to 'Stories', root_path %></li>
      <li><%= link_to 'Drafts', drafts_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_sidedraft.html.erb
<section class="sidebar-draft">
  <header>draft</header>
  <% @drafts.each do |draft| %>
  <a class="sidelink" href="#">
    <section class="sidebar-list">
    
      <div class="date">
        <div>
          <span class="month"><%= draft.diary_date.month %></span>
          <span class="day"><%= draft.diary_date.day %></span>
        </div>
        <div>
          <span class="week"><%= draft.week %></span>
        </div>
      </div>
      <div class="content"><%= simple_format(excerpt(draft.content,'',radius: 10)) %></div>
      <div class="pic">
        <%= image_tag draft.picture if draft.picture.attached? %>
      </div>
    </section>
  </a>
  <% end %>
  <%= link_to 'more...', drafts_path, class:'more' %>
</section>

app/views/layouts/_sidepocket.html.erb
<section class="sidebar-pocket">
  <header>pocket</header>
  <% @pockets.each do |pocket| %>
  <a class="sidelink" href="#">
    <section class="sidebar-list">
      <div class="date">
        <div>
          <span class="month"><%= pocket.expect_date.month %></span>
          <span class="day"><%= pocket.expect_date.day %></span>
        </div>
        <div>
          <span class="week"><%= pocket.week %></span>
        </div>
      </div>
      <% if pocket.location.try(:[], 'name') %>
      <div class="location"><%= pocket.location['name'] %></div>
      <% end %>
    </section>
  </a>
  <% end %>
  <%= link_to 'more', pockets_path ,class:'more'%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>GoGoDiary</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>